### PR TITLE
Scrolling performance improvements

### PR DESCRIPTION
**Pull request by boscojwho**
Contains various changes to further improve scrolling performance, including:
- Avoid redoing work on scroll up when post reappears.

### CODE REVIEW

**Comment by boscojwho** [comment]
Resolved a merge conflict: [94d97ce](https://github.com/Athlon007/Leomard/pull/71/commits/94d97ce9fa529a0cd5be786d6a022f7ecd994eba)

**Comment by Athlon007** [comment]
Seems like the wide-view of communities is currently borked. Community sidebar should appear up top when in small width, and to the right side when in wide mode:

Screenshot 2023-07-27 at 12 17 13
Screenshot 2023-07-27 at 12 19 27



Expected:

Screenshot 2023-07-27 at 12 19 01
Screenshot 2023-07-27 at 12 19 07

**Comment by boscojwho** [comment]
Indeed borked =/  
Bug introduced in commit b16b58e38d4f0e01af957306bdc70c01f4270391

**Comment by boscojwho** [comment]
Fixed:
- The offending commit was never meant to be committed in the first place 🥲

**Comment by Athlon007** [comment]
Thanks for the fix :)

**Pull request merged**
